# Generated by Django 5.2.5 on 2025-08-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_ticket_options_ticket_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
